# 自動更新YAML
name: test

on:
  workflow_dispatch:

  schedule:
    # - cron:  "分 時 日 月 曜日"
    - cron:  "11 2 * * *"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: "Run a generate Hello Wold"
        run: |
          git config --global user.email ${{ secrets.USER_EMAIL }}
          git config --global user.name ${{ secrets.USER_NAME }}
          echo "w" >> README.md
          git add README.md
          git commit -m '[add] Hello Wold!'
          git push origin main
